---
layout: post
title:  Java_异常处理
date: 2017-11-23
categories: Java
tages: Java_异常处理
description: 
---

#何时需要用到异常处理

   Java程序有一部分的错误可以在编译的时候就可以被发现，这一类一般属于语法错误；但是，有一部分错误是语法是正确的，运行时就会产生错误。不如以下代码：

```java
public class ExceptionDemo1 {
	public static void main(String[] args) {
		int a = 10;
		int b = 0;
		System.out.println("a/b = " + a/b);
	}
}
```

   上述代码通过 ` javac ExceptionDemo1.java ` 可以通过编译，但是使用 ` java ExceptionDemo1 ` 后报错。错误提示如下：

```
Exception in thread "main" java.lang.ArithmeticException:
/ by zero at ExceptionDemo1.main(ExceptionDemo1.java:5)
```

   错误提示信息说了在`／`后有一个0，这是一个除0错误，这个错误类型是:`ArithmeticException` 算术异常。

#检验异常和非检验异常(check Exception, uncheck Excepion)

##check Exception
这类异常是由一些外部的偶然因素所引起的。Java编译器强制要求处理。也就是说，程序必须进行对这类异常进行处理。
   check Exception 种类：
   * Exception
   * FileNotFoundException
   * IOException
   * ......  

##uncheck Exception:
这类异常是编程人员的逻辑问题。应该承担责任。Java编译器不进行强制要求处理。也就是说，这类异常再程序中，可以进行处理，也可以不处理。
   uncheck Exception 种类：
   * ArithmeticException    算术异常
   * NullPointerException   控制异常(![这种异常在前一篇提过](../2017-11-08-Java-Constructor-Summary))
   * IndexOutOfBoundException 数组越界
   * .......

#对异常处理的方式

##try{}catch(){}finally{}

以文章一开头代码为例，进行修改:

```java
public class ExceptionDemo1 {
	public static void main(String[] args) {
		try {
			int a = 10;
			int b = 0;
			System.out.println("a/b = " + a/b);
		}catch{ArithmetExcepion ex} {
			System.out.println("除数错误");
		}catch(Exception ex1) {
			System.out.println("出错～");
		}finally{
			System.out.println("finally");
		}
	}
}	
```

##使用throw显示抛出异常
   如果是check Exception后面要接try{}catch(){}来处理，如果是uncheck Exception 可以不进行处理，建议都进行处理，因为人的逻辑总会出错。

##是用throws回避异常

   同上

##自定义异常
   要继承于Exception或者Excepion的子类


##参考文章
![](http://yangshen998.iteye.com/blog/1311682)
![](http://www.cnblogs.com/mengdd/archive/2013/02/03/2890923.html)